version: '3.8'

services:
  db:
    image: postgis/postgis:latest
    container_name: postgis_db
    restart: always
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: weather_api
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      DB_HOST: db
      DB_PORT: "${DB_PORT}"
      PORT: 3000
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: ["node", "dist/server.js"]

volumes:
  pg_data:

